### ISSUE TITLE
problem with NUTANIX_IMAGE module logic

### ISSUE THREAD

**Issue by tuxtof** [ideadevice/ansible-ahv-provider-plugin#12]
The base logic of Ansible and ansible module is to be idempotent

An operation is idempotent if the result of performing it once is exactly the same as the result of performing it repeatedly without any intervening actions.

that not the case with image creation

launching the same playbook a second time give me

`"msg": "Found existing images with name centos-8-stream-20210603, use force option to create new image"}`

and the new_image_name and new_image_type options are not logic for an idempotent approach

update need to be based on the same playbook but just with change on value to update

**Comment by charanteja333** [comment]
@balugeorge  lets discuss about this internally

**Comment by tuxtof** [comment]
@yannickstruyf3 curious to have your view on this one

**Comment by yannickstruyf3** [comment]
I agree with @tuxtof.
Re-running the playbook for a second time should not throw an error. if there is an image (no images with duplicate names) present with the required name, it should check if it is fully compliant to the Ansible definition. If this is the case, no change is required. Otherwise Ansible needs to perform the required steps to make the Image object compliant. 

The new_image_name and new_image_type should be removed in my opinion. If an image needs to be renamed, the user needs to pass the image uuid and pass the image name was well. If the image object with the uuid has a different name than what is passed via Ansible, it should be renamed. Same logic appliaces to new_image_type.

**Comment by tuxtof** [comment]
perfectly agree with the detailed description, can't say better
